# Generated by Django 5.2.7 on 2025-10-12 10:28

import bma.requests.models
import django.core.serializers.json
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.UUIDField(default=bma.requests.models.generate_bill_number, editable=False, unique=True)),
                ('name', models.CharField(blank=True, verbose_name='Bill Name')),
                ('category', models.CharField(choices=[('1', 'Category 1'), ('2', 'Category 2')], default=('1', 'Category 1'), max_length=255, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Bill Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Bill Description')),
                ('razorpay_id', models.CharField(blank=True, default=None, null=True, verbose_name='Payment Id')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, verbose_name='Document Name')),
                ('template_used', models.TextField(blank=True, null=True, verbose_name='Template used to render')),
                ('file', models.FileField(max_length=255, upload_to=bma.requests.models.upload_file_path, verbose_name='Document')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Details of Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
