# Generated by Django 5.2.7 on 2025-10-14 19:57

import bma.base.utils
import bma.requests.models
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, verbose_name='Document Name')),
                ('template_used', models.TextField(blank=True, null=True, verbose_name='Template used to render')),
                ('file', models.FileField(max_length=255, upload_to=bma.requests.models.upload_file_path, verbose_name='Document')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Details of Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.UUIDField(default=bma.base.utils.generate_random_uuid, editable=False, unique=True)),
                ('name', models.CharField(blank=True, verbose_name='Bill Name')),
                ('state', models.CharField(choices=[('paid', 'Paid Bill'), ('unpaid', 'Unpaid Bill'), ('paid-in-cash', 'Bill Paid in cash'), ('payment-under-process', 'Payment under processing')], default='unpaid', max_length=255, verbose_name='Category')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Total Bill Amount')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', verbose_name='Currency')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Bill Description')),
                ('is_partial_payment', models.BooleanField(default=False, verbose_name='Is the Amount paid partially')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.baseusermodel', verbose_name='Bill Payee')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
