# Generated by Django 5.2.7 on 2025-10-19 17:34

import bma.base.utils
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_network', models.CharField(choices=[('visa', 'Visa'), ('bajaj', 'Bajaj'), ('rupay', 'Rupay'), ('diners', 'Diners'), ('maestro', 'Maestro'), ('amex', 'American Express'), ('mastercard', 'Mastercard')], verbose_name='Card Network')),
                ('number', models.CharField(verbose_name='Card Number')),
                ('name', models.CharField(verbose_name='Card User Name')),
                ('expiry_month', models.CharField(editable=False, verbose_name='Expiry Month')),
                ('expiry_year', models.CharField(editable=False, verbose_name='Expiry Month')),
                ('cvv', models.IntegerField(verbose_name='CVV/CVC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardlessEMIDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('idfb', 'IDFC Bank'), ('hdfc', 'HDFC Bank'), ('axio', 'walnut369'), ('icic', 'ICICI Bank'), ('kkbk', 'Kotak Bank'), ('earlysalary', 'Fibe'), ('zestmoney', 'ZestMoney')], verbose_name='Cardless EMI Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Internet Banking Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternetBankingDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(verbose_name='Internet Banking Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Internet Banking Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_state', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted/ Under - processing'), ('paid', 'Paid')], default='created', editable=False, verbose_name='State of order')),
                ('currency', models.CharField(choices=[('INR', 'Indian National Rupee'), ('USD', 'United State Dollar'), ('YEN', 'Chinese Yen')], default='INR', verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Order Amount')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Order Description')),
                ('exteranal_order_id', models.CharField(blank=True, editable=False, null=True, verbose_name='External Order id')),
                ('external_reciept_number', models.UUIDField(blank=True, default=bma.base.utils.generate_random_uuid, editable=False, null=True, unique=True)),
                ('responses', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Order API responses')),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayLaterDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(verbose_name='Pay Later Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Pay Later Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(verbose_name='Wallet Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Wallet Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EMIDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emi_duration', models.IntegerField(verbose_name='EMI duration')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emidetails', to='payments.carddetails', verbose_name='EMI card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInterfaces',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('interface_type', models.CharField(choices=[('create-payment', 'Create a payment'), ('create-order', 'Create an Order'), ('capture-payment', 'Capture Payment'), ('update-payment', 'Update a Payment'), ('fetch-payment', 'Fetch a Single Payment'), ('fetch-all-payment', 'Fetch All Payments')], verbose_name='Inteface Type')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Request Details')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_state', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('failed', 'Authorized but Failed'), ('captured', 'Captured')], default='created', editable=False, verbose_name='State of payment')),
                ('payment_mode', models.CharField(choices=[('upi', 'UPI'), ('emi', 'EMI'), ('card', 'Card'), ('wallet', 'E- Wallet'), ('paylater', 'Paylater'), ('cardless_emi', 'Cardless Emi'), ('netbanking', 'Internet Banking')], default='upi', verbose_name='Mode of paymen')),
                ('object_id', models.UUIDField(verbose_name='Object Id')),
                ('external_payment_id', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='External Payment Id')),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Details of Payment')),
                ('is_partial_payment', models.BooleanField(blank=True, null=True, verbose_name='Is Partial Payment')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentmodes', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='Order')),
                ('requested_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
