# Generated by Django 5.2.7 on 2025-10-14 19:57

import bma.base.utils
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_network', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('bajaj', 'Bajaj'), ('maestro', 'Maestro'), ('rupay', 'Rupay'), ('diners', 'Diners')], verbose_name='Card Network')),
                ('number', models.CharField(verbose_name='Card Number')),
                ('name', models.CharField(verbose_name='Card User Name')),
                ('expiry_month', models.CharField(editable=False, verbose_name='Expiry Month')),
                ('expiry_year', models.CharField(editable=False, verbose_name='Expiry Month')),
                ('cvv', models.IntegerField(verbose_name='CVV/CVC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardlessEMIDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('icic', 'ICICI Bank'), ('idfb', 'IDFC Bank'), ('hdfc', 'HDFC Bank'), ('kkbk', 'Kotak Bank'), ('axio', 'walnut369'), ('earlysalary', 'Fibe'), ('zestmoney', 'ZestMoney')], verbose_name='Cardless EMI Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Internet Banking Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternetBankingDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(verbose_name='Internet Banking Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Internet Banking Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_state', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted/ Under - processing'), ('paid', 'Paid')], default=('created', 'Created'), verbose_name='State of order')),
                ('payment_state', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('failed', 'Authorized but Failed'), ('captured', 'Captured')], default=('created', 'Created'), verbose_name='State of payment')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Order Amount')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', verbose_name='Currency')),
                ('reciept_number', models.UUIDField(default=bma.base.utils.generate_random_uuid, editable=False, unique=True)),
                ('partial_payment', models.BooleanField(default=False, verbose_name='Is Partial Payment')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Order Description')),
                ('order_id', models.CharField(blank=True, editable=False, null=True, verbose_name='External Order id')),
                ('responses', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Order API responses')),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayLaterDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(verbose_name='Pay Later Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Pay Later Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(verbose_name='Wallet Provider')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Wallet Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EMIDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emi_duration', models.IntegerField(verbose_name='EMI duration')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emidetails', to='payments.carddetails', verbose_name='EMI card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(editable=False, verbose_name='Object Id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentmodes', to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('card', 'Card'), ('netbanking', 'Internet Banking'), ('wallet', 'E- Wallet'), ('emi', 'EMI'), ('upi', 'UPI'), ('cardless_emi', 'Cardless Emi'), ('paylater', 'Paylater')], default='upi', verbose_name='Payment method')),
                ('external_payment_id', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='External Payment Id')),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Details of Payment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='Order')),
                ('requested_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='baseapp.baseusermodel', verbose_name='Requested by')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentmode', verbose_name='Payment Mode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
