# Generated by Django 5.2.7 on 2025-10-23 18:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'United States/Canada (+1)'), ('+44', 'United Kingdom (+44)'), ('+61', 'Australia (+61)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+81', 'Japan (+81)'), ('+86', 'China (+86)'), ('+65', 'Singapore (+65)'), ('+971', 'United Arab Emirates (+971)'), ('+27', 'South Africa (+27)'), ('+55', 'Brazil (+55)'), ('+52', 'Mexico (+52)')], default='+91', verbose_name='Contact Country Code')),
                ('phone_number', models.CharField(verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='UPIDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upi_provider', models.CharField(verbose_name='UPI service provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='requested_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.customer', verbose_name='Requested by'),
        ),
    ]
