# Generated by Django 5.2.7 on 2025-10-26 09:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'United States/Canada (+1)'), ('+44', 'United Kingdom (+44)'), ('+61', 'Australia (+61)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+81', 'Japan (+81)'), ('+86', 'China (+86)'), ('+65', 'Singapore (+65)'), ('+971', 'United Arab Emirates (+971)'), ('+27', 'South Africa (+27)'), ('+55', 'Brazil (+55)'), ('+52', 'Mexico (+52)')], default='+91', verbose_name='Contact Country Code')),
                ('phone_number', models.CharField(verbose_name='Contact Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Username')),
                ('suffix', models.CharField(blank=True, choices=[('Mr.', 'Mister Mr.'), ('Mrs.', 'Missus Mrs.'), ('Miss', 'Miss Miss'), ('Ms.', 'Ms'), ('Dr.', 'Doctor Dr.'), ('Prof.', 'Professor Prof.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Sr.', 'Sardar Sr.')], max_length=10, verbose_name='Suffix')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'United States/Canada (+1)'), ('+44', 'United Kingdom (+44)'), ('+61', 'Australia (+61)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+81', 'Japan (+81)'), ('+86', 'China (+86)'), ('+65', 'Singapore (+65)'), ('+971', 'United Arab Emirates (+971)'), ('+27', 'South Africa (+27)'), ('+55', 'Brazil (+55)'), ('+52', 'Mexico (+52)')], default='+91', verbose_name='Contact Country Code')),
                ('phonenumber', models.CharField(verbose_name='Contact Number')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'BMA User',
                'verbose_name_plural': 'BMA Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
