# Generated by Django 5.2.7 on 2025-10-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseusermodel_groups_baseusermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseusermodel',
            options={'verbose_name': 'BMA User', 'verbose_name_plural': 'BMA Users'},
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='country_code',
            field=models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'United States/Canada (+1)'), ('+44', 'United Kingdom (+44)'), ('+61', 'Australia (+61)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+81', 'Japan (+81)'), ('+86', 'China (+86)'), ('+65', 'Singapore (+65)'), ('+971', 'United Arab Emirates (+971)'), ('+27', 'South Africa (+27)'), ('+55', 'Brazil (+55)'), ('+52', 'Mexico (+52)')], default='+91', verbose_name='Contact Country Code'),
        ),
    ]
